### ISSUE TITLE
Krypton Client has been loaded multiple times.

### ISSUE THREAD

**Issue by jeanremy** [lyra/embedded-form-glue#13] opened 2019-05-07 09:53 UTC
Hi,

i'm facing this error when coming again on a previously mounted component in React : 

`kr-payment-form.min.js:49 : [Krypton-Client V4.0.9.1] Krypton Client has been loaded multiple times.`

It seems that the loadLibrary from the Glue class is not checking the good property. Currently, it's doing it this way:
```
if (typeof window.KR_CLIENT_LOADED != 'undefined') {
            return Promise.reject("Library KR already loaded");
        }
```
but the property KR_CLIENT_LOADED is not in my window object on first load. What can I check to avoid duplicate import ?
Thank you

**Comment by yyoyo** [comment] 2019-05-08 08:24
Hi.

Do you have a minimal example to reproduce the error?

Lionel.

**Comment by hms4242** [comment] 2019-05-15 12:28
Hi, I'm facing the same exact issue here but using Angular 7. Any solution to this?
Thanks

**Comment by yyoyo** [comment] 2019-05-15 15:44
Hi,

I have updated the angular example with the last version. [see the example here](https://github.com/lyra/embedded-form-glue/tree/master/examples/angular/minimal-example).

I can't reproduce it with the last version of:
- embbeded-form-glue 0.2.3
- and the last payment form library (4.0.10.1).

With domain are you using ?

**Comment by hms4242** [comment] 2019-05-17 07:43
Hi, with the new module version (`0.2.4`) I now have this issue https://github.com/lyra/embedded-form-glue/issues/15

**Comment by yyoyo** [comment] 2019-05-17 08:02
Ok, I close this ticket and we go ahead on #15.

**Closed by yyoyo** 2019-05-17 08:02 UTC
