### ISSUE TITLE
Can't load module with NextJS

### ISSUE THREAD

**Issue by remyzv** [lyra/embedded-form-glue#14] opened 2019-05-12 23:17 UTC
Hello,

First, thanks for your effort on making a react component, this is awesome !

I'm facing an issue when using the library with NextJS.

```
lyracom/embedded-form-glue/app/index.js:1
new Script
vm.js:84:7
createScript
vm.js:264:10
runInThisContext
vm.js:312:10
Module._compile
internal/modules/cjs/loader.js:694:28
Module._extensions..js
internal/modules/cjs/loader.js:745:10
Module.load
internal/modules/cjs/loader.js:626:32
tryModuleLoad
internal/modules/cjs/loader.js:566:12
Function.Module._load
internal/modules/cjs/loader.js:558:3
Module.require
internal/modules/cjs/loader.js:663:17
require
internal/modules/cjs/helpers.js:20:18
@lyracom/embedded-form-glue
webpack:/external "@lyracom/embedded-form-glue":1
> 1 | module.exports = require("@lyracom/embedded-form-glue");
```

So I tried to copy the library into my project and its working fine. Don't you need to compile the code ?

Take a look at this issue : https://github.com/zeit/next.js/issues/2080

Thanks a lot,

**Comment by yyoyo** [comment] 2019-05-15 18:25
Hi,

I have updated the embedded-vue-glue library to version 0.2.4.
I have changed the entry point to the distribution library. Itis now ES5, so it should work with your build.

I have written a [minimal example with nextJS here](https://github.com/lyra/embedded-form-glue/tree/master/examples/react/next-minimal). Hope it helps.

Happy hacking !
Lionel.

**Comment by remyzv** [comment] 2019-05-16 19:55
Helo @yyoyo ,

Thanks for your release this is working much better ! 

However, I can't make the form working in my language. 

I'm putting the language right here :
```
.then(({KR}) => KR.setFormConfig({              /* set the minimal configuration */
                    formToken: formToken,
                    'language': 'fr-FR',
                    'kr-language': 'fr-FR'
                }))
```

I tried both language parameters and nothing working, the test card block is loading first in french and then it goes english right after the form shows up.

How can I resolve this ?

Best regards

**Comment by yyoyo** [comment] 2019-05-17 08:04
Hi,

It should work but there is a known bug on our side.
It will be fixed next week.

You should use **kr-language** instead of language.

I'll keep you in touch.

**Comment by yyoyo** [comment] 2019-05-22 10:09
The new release in online.
The issue is fixed.

Lionel.

**Closed** 2019-05-22 10:09 UTC
